#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'lunasvg'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
    "plutovg-blend.c",
    "plutovg-canvas.c",
    "plutovg-font.c",
    "plutovg-matrix.c",
    "plutovg-paint.c",
    "plutovg-path.c",
    "plutovg-rasterize.c",
    "plutovg-surface.c",
    "plutovg-ft-math.c",
    "plutovg-ft-raster.c",
    "plutovg-ft-stroker.c",
    "lunasvg.cpp",
    "graphics.cpp",
    "svgelement.cpp",
    "svggeometryelement.cpp",
    "svglayoutstate.cpp",
    "svgpaintelement.cpp",
    "svgparser.cpp",
    "svgproperty.cpp",
    "svgrenderstate.cpp",
    "svgtextelement.cpp"
	]

	if bld.env.DEST_OS == 'win32':
		source += [
		]

	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../thirdparty/stb'
	]

	defines = ['RAD_TELEMETRY_DISABLED']

	libs = []

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		cxxflags = ['--std=c++17'],
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

