#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'soundsystem'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'../public/phonemeconverter.cpp',
		'../public/sentence.cpp',
		'snd_audio_source.cpp',
		'snd_dev_wave.cpp',
		'snd_io.cpp',
		'snd_wave_mixer.cpp',
		'snd_wave_mixer_adpcm.cpp',
		'snd_wave_source.cpp',
		'soundsystem.cpp',
	]

	if bld.env.DEST_OS == 'win32':
		source += [
			'../public/tier0/memoverride.cpp'
		]

	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../common'
	]

	defines = []

	libs = ['tier0','tier1','tier2','tier3','appframework','vstdlib','mathlib','lowlevel','dsound','dxguid','WinMM','User32','minimp3']

	if bld.env.DEST_OS == 'android':
		libs += ['ANDROID_SUPPORT']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

