name: Builds

on:
  workflow_dispatch:

jobs:
  builds-linux:
    strategy:
      matrix:
        include:
          - target: linux-i386-dedicated
            build_cmd: |
              chmod +x scripts/build-ubuntu-i386.sh
              scripts/build-ubuntu-i386.sh -d
          - target: linux-amd64-dedicated
            build_cmd: |
              chmod +x scripts/build-ubuntu-amd64.sh
              scripts/build-ubuntu-amd64.sh -d
          
    name: Build ${{matrix.target}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source (shallow clone)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive
        
      - name: Build ${{matrix.target}}
        run: |
          ${{matrix.build_cmd}}
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: csso-${{matrix.target}}
          path: ./output/*

  builds-windows:
    strategy:
      matrix:
        include:
          - target: windows-i386-dedicated
            build_cmd: |
              ./waf.bat configure -T release --build-games=csso -4 -d --disable-warns --prefix="./output"
              ./waf.bat install
          - target: windows-i386
            build_cmd: |
              ./waf.bat configure -T release --build-games=csso -4 --enable-opus --disable-warns --prefix="./output"
              ./waf.bat install
    name: Build ${{matrix.target}}
    runs-on: windows-latest

    steps:
      - name: Checkout source (shallow clone)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive
        
      - name: Build ${{matrix.target}}
        run: |
          ${{matrix.build_cmd}}
          Get-ChildItem -Path "./output" -Include *.pdb,*.lib -Recurse | Remove-Item -Force
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: csso-${{matrix.target}}
          path: ./output/*

  builds-android:
    strategy:
      matrix:
        include:
          - target: android-aarch64
            build_cmd: |
              chmod +x scripts/build-android-aarch64.sh
              scripts/build-android-aarch64.sh
    name: Build ${{matrix.target}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source (shallow clone)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive
        
      - name: Build ${{matrix.target}}
        run: |
          ${{matrix.build_cmd}}
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: csso-${{matrix.target}}
          path: ./output/*