name: Tests

on:
  workflow_dispatch:

jobs:
  tests-linux:
    strategy:
      matrix:
        include:
          - target: linux-i386
            build_cmd: |
              chmod +x scripts/tests-ubuntu-i386.sh
              scripts/tests-ubuntu-i386.sh
          - target: linux-amd64
            build_cmd: |
              chmod +x scripts/tests-ubuntu-amd64.sh
              scripts/tests-ubuntu-amd64.sh
    name: Test ${{matrix.target}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source (shallow clone)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
        
      - name: Test ${{matrix.target}}
        run: |
          ${{matrix.build_cmd}}
  
  tests-windows:
    strategy:
      matrix:
        include:
          - target: windows-i386
            build_cmd: |
              ./waf.bat configure -T release --tests --prefix=out/ --32bits
              ./waf.bat install
              cd out
              $env:Path = "bin";
              ./unittest.exe
          - target: windows-amd64
            build_cmd: |
              ./waf.bat configure -T release --tests --prefix=out/
              ./waf.bat install
              cd out
              $env:Path = "bin";
              ./unittest.exe
    name: Test ${{matrix.target}}
    runs-on: windows-latest

    steps:
      - name: Checkout source (shallow clone)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
        
      - name: Test ${{matrix.target}}
        run: |
          ${{matrix.build_cmd}}
