#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'lowlevel'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		#'device_dsound.cpp',
		'device_null.cpp',
            #'device_xaudio2.cpp',
		'device_sdl.cpp',
		'mix.cpp',
		'simple_filter.cpp',
		#'windows_audio.cpp',
	]
	
	if bld.env.DEST_OS == 'win32':
		source += [
			#'../public/tier0/memoverride.cpp'
		]

	includes = [
		'.',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../thirdparty/stb',
		'../../thirdparty/SDL2'
	]

	defines = []

	libs = ['dsound','dxguid','SDL2']
	
	#if bld.env.DEST_OS == 'win32':
	#	libs += ['NVTC', 'ATI_COMPRESS_MT_VC10']

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

